const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const core=vm.createContext({TextEncoder});vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],core);
const seeded=()=>{let state=6942;return ()=>((state=(Math.imul(state,1664525)+1013904223)>>>0)/2**32);};
const families=['eighth','triplet','sixteenth','quintuplet','sextuplet'];
const selection=Object.fromEntries(families.map(type=>[type,{notes:true,rests:true,dotted:type==='eighth'}]));
const original=core.makeEtude(64,selection,0.3,seeded());
const saved=JSON.stringify(original);
const rhythm=etude=>JSON.stringify(etude.measures.map(m=>m.map(({accented,...e})=>e)));
let previous=new Set();
for(const chance of [0,0.05,0.25,0.5,0.75,1]) {
  const exercise=core.addEtudeAccents(original,chance,seeded());
  assert.equal(rhythm(exercise),rhythm(original),'Adding accents preserves every note, rest, beat boundary and onset');
  const events=exercise.measures.flat(),notes=events.filter(e=>!e.rest),accents=notes.filter(e=>e.accented);
  assert.ok(events.filter(e=>e.rest).every(e=>!e.accented),'Rests never have accents');
  if(chance===0)assert.equal(accents.length,0);
  else if(chance===1)assert.equal(accents.length,notes.length);
  else assert.ok(Math.abs(accents.length/notes.length-chance)<0.06);
  const marked=new Set(events.map((e,i)=>e.accented?i:-1).filter(i=>i>=0));
  for(const position of previous)assert.ok(marked.has(position),'Increasing the probability retains accents for the same random sample');
  previous=marked;
  const plan=core.makePlaybackPlan(exercise,120,true);
  const drums=plan.sounds.filter(s=>['drum','softDrum'].includes(s.kind));
  assert.equal(drums.length,notes.length);
  assert.ok(drums.every((s,i)=>s.kind===(chance===0||notes[i].accented?'drum':'softDrum')));
  const oldPlan=core.makePlaybackPlan(original,120,true);
  assert.deepEqual(Array.from(plan.sounds,s=>s.at),Array.from(oldPlan.sounds,s=>s.at));
  assert.equal(plan.duration,oldPlan.duration);
  assert.equal((core.scoreSVG(exercise,2).match(/class="accent-mark"/g)||[]).length,accents.length);
  assert.equal((core.scorePDFPages(exercise).join('').match(/class="accent-mark"/g)||[]).length,accents.length);
}
assert.equal(JSON.stringify(original),saved,'The source rhythm is not mutated');
const off=core.addEtudeAccents(core.addEtudeAccents(original,1),0,()=>{throw Error('Disabled accents should not consume randomness');});
assert.ok(off.measures.flat().every(e=>!e.accented),'Turning off clears every accent');
const silent=core.addEtudeAccents(core.makeEtude(8,{sixteenth:{rests:true}},0.99),1);
assert.equal(core.makePlaybackPlan(silent,80).sounds.length,0);
assert.ok(silent.measures.flat().every(e=>!e.accented));
for(const invalid of [-0.01,1.01,NaN,Infinity])assert.throws(()=>core.addEtudeAccents(original,invalid),/от 0 до 100/);
const slider=html.match(/<input\b[^>]*id="etude-accent-chance"[^>]*>/)[0];
for(const attribute of ['type="range"','min="0"','max="100"','step="5"','value="0"','aria-valuetext="Выкл."'])assert.ok(slider.includes(attribute));
console.log('PASS: etude accents off by default, 0–100% density, rests excluded, unchanged rhythm, dynamics, SVG/PDF and disabling.');
